name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 23f2003812@ds.study.iitm.ac.in
        run: echo "Hello World"
